### ISSUE TITLE
Update gvf_validator.pl to use correct ontology file

### ISSUE THREAD

**Issue by thefferon** [The-Sequence-Ontology/GAL#1]
Line 1994 of the SO GVF validator, **gvf_validator.pl**, uses the obsolete page:

http://www.sequenceontology.org/resources/obo_files/current_release.obo

It should be updated to use the following page instead:

https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-xp.obo

This is being opened to replace https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/365, which will be closed.

**Comment by thefferon** [comment]
@barrymoore ,

Do I have this right? Should **gvf_validator.pl** be updated to point to the so-xp.obo file on GutHub? If I am wrong, I'll close this issue.

Thanks,
Tim

**Comment by cmungall** [comment]
I recommend using PURLs rather than using a URL that may change in the 
future

http://purl.obolibrary.org/obo/so.obo
http://purl.obolibrary.org/obo/so.owl

**Comment by barrymoore** [comment]
I've updated to gvf_validator, gff3_validator and gff_tool to point to the PURL location of the SO obo file (http://purl.obolibrary.org/obo/so.obo) as suggested by @thefferon and @cmungall. Changes committed and pushed to git.
