### ISSUE TITLE
GAL website redirection

### ISSUE THREAD

**Issue by SchwarzMarek** [The-Sequence-Ontology/GAL#3]
Hi,

I've ended up here after failed attempts to download GAL library from http://www.sequenceontology.org/software/GAL.html

For the sake of fellow researchers could you add links / make the download link to redirect here?

Best regards

**Comment by keilbeck** [comment]
Sorry about the confusion. I will update the link and let you know.

**Comment by srynobio** [comment]
Hello,

Thanks for bring this issue to our attention.  Could you please provide the webpage that offered the dead link.  I believed I had remove and replaced all of them to our GitHub link (https://github.com/The-Sequence-Ontology/GAL) but apparently I missed one.


— Shawn Rynearson

**Comment by SchwarzMarek** [comment]
The linked page, the download section - I get blocked by the server - I assumed that it should redirect to github.

![image](https://user-images.githubusercontent.com/25510773/54712522-c9fe6180-4b4c-11e9-9e63-ffe304bfa5ca.png)

**Comment by keilbeck** [comment]
The power went out in the server room. I'm working on it.

**Comment by srynobio** [comment]
@SchwarzMarek @keilbeck this should now be updated.  Any other issues @SchwarzMarek, let us know.

**Comment by mmokrejs** [comment]
Hi,
  I used to (actually Gentoo Linux) to fetch the release tarball from http://www.sequenceontology.org/software/GAL_Code/GAL_0.2.2.tar.gz , which is not working anymore. I cannot find a way to (re-)fetch the current sources nor a place to get newer ones.

  Please provide releases through https://github.com/The-Sequence-Ontology/GAL/releases , and make sure they extract into e.g. ./GAL-0.2.2/ (which is a good common habbit). I am looking for the following file:
```
GAL_0.2.2.tar.gz 108786594 BLAKE2B c66a22d3623278317e9feb18938faea33bbb114df153e684bb2c6b1bf6c1c2a13c6bd3306497d80ff066fa65301fdde74e70dc33f73757e9f4bf34074e145780 SHA512 a90b396b7a703da875c2b7ad67a86f477f5b98e68353c94ab7d5876e613bfe386ba8f59d130c4f8fc62e2137742256e95ba9686c14f21b85b21d64fdc4c1be1b
```

  Also, please include the link to your https://github.com/The-Sequence-Ontology/GAL/blob/master/README.md .

Thank you.

**Comment by srynobio** [comment]
@mmokrejs we currently do not offer releases of GAL.  It must be clone and build.  Would a container work better for your needs?

**Comment by mmokrejs** [comment]
@srynobio Not really, in general Gentoo compiles/installs all packages from sources. In this case it is just about placing the `*.pm` and `*.pl` files into proper locations. I will wait until you restore the files for download somewhere again. Github can automatically prepare `*.zip` and `*.tar.gz` files for you on the https://github.com/The-Sequence-Ontology/GAL/releases page. That would be the common approach.
